site:
  name: 'OmNova'
  site: 'https://omnova.ai'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: ''

metadata:
  title:
    default: 'OmNova - Hire Genius-Level AI Teams'
    template: '%s â€” OmNova'
  description: 'For the first time, organizations of any size can access expert-level intelligence, working 24/7, tailored precisely to their challenges.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: 'OmNova'
    images:
      - url: '~/assets/images/hero-image.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@omnova'
    site: '@omnova'
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: false
    postsPerPage: 6

analytics:
  vendors:
    googleAnalytics:
      id: null

ui:
  theme: 'system'
